-- sql para criar o banco de dados
CREATE DATABASE `banco`;

CREATE TABLE `banco`.`usuarios` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `nome` VARCHAR(50) NOT NULL,
    `senha` VARCHAR(10) NOT NULL,
    `cargo` VARCHAR(50) NOT NULL,
    PRIMARY KEY (`id`)
) ENGINE = InnoDB;

INSERT INTO `usuarios` (`nome`, `senha`, `cargo`) VALUES
('Fernanda Carlos', '8013', 'usuario'),
('João Beatriz', '3082', 'usuario'),
('Débora Daniel', '1820', 'usuario'),
('Priscila Amanda', '9251', 'editor'),
('Patrícia Simone', '6450', 'editor'),
('André Daniel', '6374', 'admin'),
('Jéssica Carlos', '6734', 'admin'),
('Marcelo Vanessa', '7124', 'editor'),
('Gustavo Vinícius', '8763', 'usuario'),
('Vinícius Gustavo', '2295', 'editor'),
('João Mariana', '3917', 'admin'),
('Fábio Mariana', '4594', 'editor'),
('Carlos Hugo', '3891', 'admin'),
('Roberto Jéssica', '2004', 'usuario'),
('Simone Bruno', '2854', 'usuario'),
('Vinícius Rafael', '6441', 'admin'),
('Larissa Isabela', '4370', 'admin'),
('Patrícia Juliana', '9762', 'admin'),
('Rafael Isabela', '4802', 'usuario'),
('Tatiane Marcos', '3513', 'usuario'),
('Felipe Fernanda', '9439', 'usuario'),
('Sérgio Marcos', '1215', 'editor'),
('Tatiane Débora', '4515', 'usuario'),
('Carlos Rodrigo', '4758', 'admin'),
('Hugo Marcos', '6909', 'editor'),
('Carlos Cristiane', '5895', 'usuario'),
('Camila Aline', '9825', 'usuario'),
('Gustavo Rafael', '7185', 'admin'),
('Eduardo Vinícius', '2650', 'usuario'),
('Vanessa Pedro', '9635', 'editor'),
('Beatriz Fábio', '5532', 'admin'),
('Felipe Felipe', '4418', 'admin'),
('Bruno Bruno', '3160', 'usuario'),
('Natália Thiago', '7465', 'admin'),
('João Elaine', '9850', 'editor'),
('Natália Tatiane', '4018', 'editor'),
('Mateus Fábio', '6874', 'admin'),
('Carlos André', '7893', 'usuario'),
('André Beatriz', '5667', 'editor'),
('Ana João', '3261', 'admin'),
('Renata Bianca', '4844', 'editor'),
('Isabela Camila', '3334', 'admin'),
('Ana Sérgio', '1585', 'usuario'),
('Débora Fábio', '2976', 'editor'),
('Diego Cristiane', '6799', 'usuario'),
('Luana Tatiane', '3063', 'editor'),
('Pedro Marcelo', '3287', 'usuario'),
('Fábio Juliana', '2239', 'admin'),
('Isabela Rafael', '7154', 'editor'),
('Thiago Leonardo', '8796', 'admin');
